import "./globals.css";
import { AuthProvider } from "@/app/AuthProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { useTheme } from "next-themes";
import {Toaster as Sonner}  from "sonner";
// import { Toaster } from "sonner";

export const metadata = {
  title: "PaperKeep",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Sonner
              className="toaster group"
              visibleToasts={4}
              toastOptions={{
                classNames: {
                  toast:
                    "group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:border-border group-[.toaster]:shadow-lg",
                  description: "group-[.toast]:text-muted-foreground",
                  actionButton:
                    "group-[.toast]:bg-primary group-[.toast]:text-primary-foreground",
                  cancelButton:
                    "group-[.toast]:bg-muted group-[.toast]:text-muted-foreground",
                },
              }}
            />
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
