import "./globals.css";
import { AuthProvider } from "@/app/AuthProvider";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "PaperKeep",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
